name: TEST CODE CI

on:
    pull_request:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "14"

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

            - name: Check for Test Failures
              id: check-test-failures
              run: |
                  test_result=$(npm test --json)
                  echo "$test_result" > test-result.json
                  if grep -q "\"failure\": true" test-result.json; then
                    echo "Tests failed. Cancelling Pull Request..."
                    echo "::set-output name=cancel-pr::true"
                  else
                    echo "Tests passed. Continuing with Pull Request..."
                    echo "::set-output name=cancel-pr::false"
                  fi

            - name: Cancel Pull Request
              if: steps.check-test-failures.outputs.cancel-pr == 'true'
              uses: superbrothers/close-pull-request@v3
              with:
                  comment: "Tests failed. Pull Request cancelled."
                  github_token: ${{ secrets.GITHUB_TOKEN }}
