name: CI

on:
    pull_request:
        branches:
            - feature/ci

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_USER: test
                    MYSQL_PASSWORD: test
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: ywc
                ports:
                    - 3306
                options: >-
                    --health-cmd="mysqladmin ping"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 1

            - name: List files in repository
              run: |
                  ls -R
                  mysql_config --socket

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Verify MySQL connection from host
              run: |
                  mysql --version
                  sudo apt-get install -y mysql-client
                  sudo service mysql start
                  mysql -uroot -proot -e "CREATE DATABASE ywc"
                  mysql -uroot -proot -e "USE ywc; {{ secrets.CHECK_DATA }}"
                  mysql -uroot -proot -e "USE ywc; {{ secrets.CREATE_TABLE }}"
                  mysql -uroot -proot -e "USE ywc; {{ secrets.INSERT_DATA }}"
                  mysql -uroot -proot -e "SHOW DATABASES"

            - name: Make .env file
              uses: SpicyPizza/create-envfile@v1
              with:
                  envkey_MYSQL_HOST: 127.0.0.1
                  envkey_MYSQL_PORT: 3306
                  envkey_MYSQL_USERNAME: root
                  envkey_MYSQL_PASSWORD: root
                  envkey_MYSQL_SCHEMA: ywc
                  envkey_APP_NAME: MyApp
                  envkey_APP_PORT: 3000
                  envkey_APP_CORS_ORIGINS: http://localhost:8080/
                  envkey_APP_WEB_URL: http://localhost:8080/
                  file_name: .env.test

            - name: Install dependencies and run tests
              run: |
                  sudo service mysql restart
                  cp ${{ github.workspace }}/.env.test ${{ github.workspace }}/.env.local
                  sudo cat ${{ github.workspace }}/.env.test
                  npm install
                  npm test
              env:
                  CI: true
                  MYSQL_DATABASE: ywc
                  DB_USERNAME: root
                  DB_PASSWORD: root
                  DB_PORT: 3306

            - name: Handle failure
              uses: actions/github-script@v3
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const ref = "${{ github.ref }}"
                      const pull_number = Number(ref.split("/")[2])
                      await github.pulls.createReview({
                        ...context.repo,
                        pull_number,
                        body: "테스트코드를 다시 확인해주세요.",
                        event: "REQUEST_CHANGES"
                      })
                      await github.pulls.update({
                        ...context.repo,
                        pull_number,
                        state: "closed"
                      })
              if: failure()
